### ISSUE TITLE
Octoprint addon - Own Server - HTTPS Lockup

### ISSUE THREAD

**Issue by MidnightLink** [TheSpaghettiDetective/TheSpaghettiDetective#191]
Hosting my own TSD server.

If you have https put in instead of http when adding your own server address and click save it will freeze the TSD plugin/octoprint and the server will need to be rebooted.

**Comment by kennethjiang** [comment]
@MidnightLink this is probably caused by some networking setup. TSD production is https so the code obviously works with https.

Please dig a bit deeper and post more details here. Please come to our private server discord channel you need assistance on how to debug this problem: https://discord.gg/Cn9Hde

**Comment by RaymondHimle** [comment]
I could not reproduce this issue in my test environment.

**Comment by RaymondHimle** [comment]
@kennethjiang This can be closed due to inactivity.
