### ISSUE TITLE
(Bug) TSD detects false fails in print.

### ISSUE THREAD

**Issue by BlackJack070786** [TheSpaghettiDetective/TheSpaghettiDetective#419]
I have an Ender 5 (stock) in the Creality enclosure. TSD is detecting the Z end stop switch as well as the enclosure background as failed (potential failing) prints. With "Watch for failures" turned on; TSD will notify me about the potential failing of a pring when the print head reveals the Z end stop switch. On one occasion; TSD notified me that my print was failing because of the background (enclosure wall). TSD will continually notify me about my "potential print failure" with the Z end stop switch until it finally gives up and calls it a failure at which point it will pause the print. The only "fix" that I can think of currently is to cover the background area as well as the Z end stop switch with something less reflective. I have not tested my work around yet. Is there a special position for me to pur the camera to not cause this problem?

**Comment by kennethjiang** [comment]
Some users do run into more false alarms than others. It's almost impossible to completely eliminate false alarms, since we don't "program" the AI algorithm. The algorithm "learned from training data by itself". Even the state of the art AI technology can't eliminate false detections completely. For instance, Apple's face id makes mistakes all the time.

We are trying our best to improve the accuracy of the algorithm as fast as we can, while trying to keep the false alarm rate low. In the mean time, here are a few simple techniques other TSD users are using to work around false alarms: https://www.thespaghettidetective.com/docs/failure-detection-false-alarms/
