### ISSUE TITLE
[BUG] `web/static_build` folder is built into the image

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/TheSpaghettiDetective#619]
We have [.dockerignore](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/web/.dockerignore) so that the big folders that are not needed in building the image are not included in the image, when the self-hosted server is rebuilt with `docker-compose up --build -d`.

But it seems `web/static_build` is still included in the resulted docker image and made it really big. Need to investigate if the role of `.dockerignore` is misunderstood. If so, we need to figure out another way to achieve the same goal.

**Comment by kennethjiang** [comment]
Confirmed `.dockerignore` actually solved this problem.

**Comment by marc0777** [comment]
I think this issue still applies on [release](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/tree/release) since the `web` folder has been moved to `backend`, but the `.dockerignore` [there](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/release/.dockerignore) still references `web/static_files`.

**Comment by kennethjiang** [comment]
Good point. This bug will be fixed on `release` branch with our next release, which will be soon.
